<?php

namespace App\Console;

use App\Jobs\ProcessPodcast;
use App\User;
use DateTimeZone;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use Illuminate\Support\Facades\Artisan;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        //
    ];

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__.'/Commands');

        Artisan::command('question', function () {
            $name = $this->ask('What is your name?');

            $language = $this->choice('Which language do you program in?', [
                'PHP',
                'Ruby',
                'Python',
            ]);

            $this->line('Your name is '.$name.' and you program in '.$language.'.');
        });

        require base_path('routes/console.php');
    }

    /**
     * 스캐쥴 잡 타임존 셋팅
     *
     * @return DateTimeZone|string|null
     */
    protected function scheduleTimezone()
    {
        return 'Asia/Seoul'; // TODO: Change the autogenerated stub
    }

    /**
     * 어플리케이션 스케쥴 잡 정의
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {

    }
}
